### ISSUE TITLE
tinkr update updates show() arguments

### ISSUE THREAD

**Issue by froggleston** [carpentries/pegboard#156]
{tinkr} has been updated to include a `lines` argument to the show() function. As a result, tests now fail: https://github.com/carpentries/pegboard/actions/runs/9654324453/job/26628333247#step:6:286

https://github.com/ropensci/tinkr/pull/108

**Comment by zkamvar** [comment]
ugh, I'm sorry about this. I forgot that our universe was using the dev version of {tinkr}.

**Comment by froggleston** [comment]
No worries - I caught it as I just so happened to check through the failed workflow emails this morning! :)
