### ISSUE TITLE
Link validation: allow 'R' as single-letter link text

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/pegboard#91]
At the moment I get a `text too short' warning from link validation wherever I link from 'R' in my lesson content. Most single-letter links are probably errors/opportunities for improvement, but I think this is an exception. See the example below, taken from the source of https://carpentries.github.io/lesson-development-training/instructor/07-infrastructure.html#using-the-carpentries-workbench: 

```Markdown
Instead, the lessons are built using a programming language, _[R]_, 
and _[pandoc]_,  a software designed for converting content between file formats.

[pandoc]: https://pandoc.org/
[R]: https://www.r-project.org/ 
```

**Comment by zkamvar** [comment]
I don't think this should be an exception for two reasons:

1. Single-letter links are an accessibility issue for users who have motor disabilities, but do not use screen readers. From the [WebAIM link text techniques page](https://webaim.org/techniques/hypertext/link_text#link_length):
   > The danger in using single characters as links—or in using any sort of small link (such as a 10 pixel by 10 pixel graphic)—is that some users will have difficulty clicking on such a small area. Someone with cerebral palsy, for example, may be able to use the hands to manipulate a mouse, but may have difficulty with the precise movements and muscle control necessary to click on a small link.
2. There are a quite a number of languages with single letter names (B, C, D, R, and S come to mind immediately)


My suggestion would be to wrap the link in the larger context:


```markdown
Instead, the lessons are built using [a programming language, _R_][R], 
and _[pandoc]_,  a software designed for converting content between file formats.

[pandoc]: https://pandoc.org/
[R]: https://www.r-project.org/ 
```

Instead, the lessons are built using [a programming language, _R_][R], 
and _[pandoc]_,  a software designed for converting content between file formats.

[pandoc]: https://pandoc.org/
[R]: https://www.r-project.org/

**Comment by tobyhodges** [comment]
Ok, I like that suggestion and will implement it. Thanks for the thoughtful response, @zkamvar
